### ISSUE TITLE
CSS percentage calculating

### ISSUE THREAD

**Issue by wahaha2012** [wahaha2012/wahaha2012.github.io#47]
html>body>section>div>p
```css
section {
  position: absolute;
  left: 30px;
  top: 30px;
  width: 400px;
  height: 160px;
  padding: 30px 20px;
}
p {
  width: 50%;   /* == (400px + 20px + 20px) * .5 = 220px */
  height: 25%;  /* == (160px + 30px + 30px) * .25 = 55px */
  margin: 5%;   /* == (400px + 20px + 20px) * .05 = 22px */
  padding: 5%;  /* == (400px + 20px + 20px) * .05 = 22px */
}
```

### Refer
[1] https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block
